-- MySQL Script generated by MySQL Workbench
-- Sat Feb 19 09:34:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Optica` ;

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(120) NULL,
  `telefono` VARCHAR(9) NULL,
  `fax` VARCHAR(9) NULL,
  `NIF` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Gafas` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Gafas` (
  `id_gafa` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NULL,
  `color_gafa` VARCHAR(45) NULL,
  `color_lentes` VARCHAR(45) NULL,
  `pvp` FLOAT NOT NULL,
  `Grad_OD` VARCHAR(45) NULL,
  `Grad_OI` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gafa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_registro` DATE NULL,
  `atendido por` VARCHAR(45) NULL,
  `cliente nuevo` VARCHAR(2) BINARY NULL,
  `recomendado por` ENUM('si', 'no') NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`compras` ;

CREATE TABLE IF NOT EXISTS `Optica`.`compras` (
  `id_cliente` INT NOT NULL,
  `id_gafa` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_gafa`),
  INDEX `fk_Clientes_has_Gafas_Gafas1_idx` (`id_gafa` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Gafas_Clientes_idx` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `Gafas_marca_UNIQUE` (`id_gafa` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Gafas_Clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Optica`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Gafas_Gafas1`
    FOREIGN KEY (`id_gafa`)
    REFERENCES `Optica`.`Gafas` (`id_gafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`suministro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`suministro` ;

CREATE TABLE IF NOT EXISTS `Optica`.`suministro` (
  `id_gafa` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_gafa`, `id_proveedor`),
  INDEX `fk_Proveedor_has_Gafas_Gafas1_idx` (`id_proveedor` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Gafas_Proveedor1_idx` (`id_gafa` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_has_Gafas_Proveedor1`
    FOREIGN KEY (`id_gafa`)
    REFERENCES `Optica`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Gafas_Gafas1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Optica`.`Gafas` (`id_gafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
